const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {PGlite}=require('@electric-sql/pglite');

test('panel de jugadoras: aislamiento, asistencia, vinculos y participacion real',async context=>{
 const db=new PGlite();context.after(()=>db.close());
 await db.exec(`
 create role anon;create role authenticated;create schema auth;
 grant usage on schema public,auth to anon,authenticated;
 create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz default now());
 create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create table organizations(id uuid primary key,status text default 'active');
 create table organization_members(organization_id uuid references organizations,user_id uuid references auth.users,role text,status text default 'active');
 create table teams(id uuid primary key,organization_id uuid references organizations,status text default 'active',public_site_enabled boolean default true);
 create table players(id uuid primary key,team_id uuid references teams,first_name text,last_name text,jersey_number int,position text,photo_url text,active boolean default true);
 create table matches(id uuid primary key,team_id uuid references teams,league_id uuid,match_date date,match_time time,opponent_name text,venue text,status text default 'scheduled',goals_for int default 0,goals_against int default 0);
 create table match_events(id uuid primary key default gen_random_uuid(),team_id uuid,match_id uuid references matches,player_id uuid references players,event_type text,annulled boolean default false);
 create table match_rosters(id uuid primary key default gen_random_uuid(),team_id uuid references teams,match_id uuid references matches,player_id uuid references players,role text default 'available',unique(match_id,player_id));
 create function has_org_role(p_org uuid,p_roles text[]) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from organization_members where organization_id=p_org and user_id=auth.uid() and role=any(p_roles) and status='active')$$;
 create function is_org_member(p_org uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from organization_members where organization_id=p_org and user_id=auth.uid() and status='active')$$;
 create function team_org(p_team uuid) returns uuid language sql stable security definer set search_path=public as $$select organization_id from teams where id=p_team$$;
 alter table match_rosters enable row level security;
 create policy "public match rosters" on match_rosters for select using(true);
 create policy "staff manage match rosters" on match_rosters for all using(has_org_role(team_org(team_id),array['owner','admin','capturista','entrenador'])) with check(true);
 grant select on match_rosters,players,matches,match_events,teams to anon,authenticated;
 grant insert,update,delete on match_rosters to authenticated;
 `);
 const migration=fs.readFileSync('supabase/05_PANEL_JUGADORAS.sql','utf8');await db.exec(migration);await db.exec(migration);
 const id=number=>`00000000-0000-4000-8000-${String(number).padStart(12,'0')}`;
 const org=id(1),otherOrg=id(2),team=id(3),otherTeam=id(4),owner=id(10),coach=id(11),user=id(12),otherUser=id(13),capture=id(14),athlete=id(20),otherAthlete=id(21),foreignAthlete=id(22),match=id(30),cancelled=id(31),future=id(32);
 await db.query('insert into organizations(id) values($1),($2)',[org,otherOrg]);
 await db.query('insert into teams(id,organization_id) values($1,$2),($3,$4)',[team,org,otherTeam,otherOrg]);
 for(const [account,email,role] of [[owner,'owner@test.example','owner'],[coach,'coach@test.example','entrenador'],[user,'jessica@test.example','viewer'],[otherUser,'andrea@test.example','viewer'],[capture,'capture@test.example','capturista']]){
  await db.query('insert into auth.users(id,email) values($1,$2)',[account,email]);
  await db.query('insert into organization_members(organization_id,user_id,role) values($1,$2,$3)',[org,account,role]);
 }
 await db.query("insert into players(id,team_id,first_name) values($1,$2,'Jessica'),($3,$2,'Andrea'),($4,$5,'Otra')",[athlete,team,otherAthlete,foreignAthlete,otherTeam]);
 await db.query("insert into matches(id,team_id,status) values($1,$2,'scheduled'),($3,$2,'cancelled'),($4,$2,'scheduled')",[match,team,cancelled,future]);
 async function asUser(account){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[account||'']);await db.exec('set role authenticated');}
 const link=(player,email)=>db.query('select set_player_account($1,$2)',[player,email]);
 const mark=(game,player,role='available',attendance='pending',played=false)=>db.query('select set_match_attendance($1,$2,$3,$4,$5)',[game,player,role,attendance,played]);
 const portal=async(selected=team)=>(await db.query('select player_dashboard($1) as result',[selected])).rows[0].result;
 const coachData=async()=>(await db.query('select coach_attendance($1) as result',[team])).rows[0].result;
 await asUser(owner);await link(athlete,'JESSICA@test.example');await link(otherAthlete,'andrea@test.example');
 await assert.rejects(link(otherAthlete,'jessica@test.example'),/otra ficha/);
 await assert.rejects(link(foreignAthlete,'jessica@test.example'),/administradores/);
 await assert.rejects(link(athlete,'missing@test.example'),/membresia activa/);
 assert.equal((await coachData()).players.find(player=>player.id===athlete).email,'jessica@test.example');
 await asUser(coach);await assert.rejects(link(athlete,'andrea@test.example'),/administradores/);
 await mark(match,athlete);await mark(match,otherAthlete);await mark(future,athlete);
 assert.equal((await coachData()).players[0].email,null);
 await assert.rejects(mark(match,foreignAthlete),/Sin permiso/);
 await assert.rejects(mark(cancelled,athlete),/cancelados/);
 await assert.rejects(mark(match,athlete,'available','absent'),/iniciar o finalizar/);
 await asUser(user);
 assert.equal((await portal()).player.id,athlete);
 assert.equal((await portal(otherTeam)).player,null);
 await db.exec('reset role');
 await db.query("insert into matches(id,team_id) values($1,$2)",[id(40),otherTeam]);
 await db.query("insert into match_rosters(team_id,match_id,player_id) values($1,$2,$3)",[otherTeam,id(40),athlete]);
 await asUser(user);
 assert.equal((await db.query('select * from match_rosters')).rows.length,2);
 await assert.rejects(coachData(),/Sin permiso/);
 await assert.rejects(mark(match,athlete,'starter','present',true),/Sin permiso/);
 await assert.rejects(db.query("update match_rosters set attendance='present'"),/permission denied/);
 await assert.rejects(db.query('select * from player_accounts'),/permission denied/);
 await db.query("select set_my_availability($1,'yes')",[match]);
 assert.equal((await portal()).matches.find(game=>game.id===match).availability,'yes');
 await asUser(otherUser);assert.equal((await portal()).matches.find(game=>game.id===match).availability,'pending');
 await asUser(capture);await assert.rejects(mark(match,athlete),/Sin permiso/);
 await db.exec('reset role');await db.query("update matches set status='finished' where id=$1",[match]);
 await db.query("insert into match_events(team_id,match_id,player_id,event_type) values($1,$2,$3,'goal')",[team,match,athlete]);
 await asUser(coach);await mark(match,athlete,'starter','present',true);await mark(match,otherAthlete,'available','excused');
 await assert.rejects(mark(match,athlete,'out','absent'),/no convocada/);
 await assert.rejects(mark(match,athlete,'starter','absent',true),/presente/);
 await asUser(user);await assert.rejects(db.query("select set_my_availability($1,'no')",[match]),/no admite/);
 const result=await portal();assert.equal(result.matches.find(game=>game.id===match).goals,1);assert.equal(result.matches.find(game=>game.id===match).played,true);
 assert.equal((await db.query('select player_match_count($1) as count',[athlete])).rows[0].count,1);
 assert.equal((await db.query('select player_match_count($1) as count',[otherAthlete])).rows[0].count,0);
 await db.exec('set role anon');assert.equal((await db.query('select * from match_rosters')).rows.length,0);
 assert.equal((await db.query('select player_match_count($1) as count',[athlete])).rows[0].count,1);
 await assert.rejects(portal(),/permission denied/);
 await asUser(coach);await mark(future,athlete,'out');
 await asUser(user);await assert.rejects(db.query("select set_my_availability($1,'yes')",[future]),/convocatoria/);
 await db.exec('reset role');await db.query("update organization_members set status='disabled' where user_id=$1",[user]);
 await asUser(user);assert.equal((await portal()).player,null);
 await asUser(owner);await link(athlete,null);
 await db.exec('reset role');assert.equal((await db.query('select count(*)::int as count from player_accounts where player_id=$1',[athlete])).rows[0].count,0);
});